# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.11.0"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Display info about Jodel apk"
  lane :j_info do
    app_info(file: "jodel/base.apk")
  end
  
  lane :adb_connect do |options|
    adb(
      command: "connect " + options[:ip] + ":5555"
    )
  end
  
  desc "Get the apk from a connect device"
  lane :j_get do
    apk_path = adb(
      command: "shell pm path com.tellm.android.app"
    ).split("package:")[1].delete("\n").delete("\r")
    adb(
      command: "pull -a #{apk_path} jodel"
    )
    app_info(file: "jodel/base.apk")
  end
  
  desc "Decompile base.apk"
  lane :j_decompile do
    get_android_version(apk: "jodel/base.apk")
    out_folder = "out-#{lane_context[SharedValues::GET_ANDROID_VERSION_NAME]}"    
    sh "cd ../jodel && jadx -d #{out_folder} base.apk > /dev/null"
  end

  desc "Install debug JX on device"
  lane :jx_dinstall do |options|
    if adb_devices.any?
      gradle(task: "installDebug")
    elsif options[:ip]
      unless adb_connect(ip:options[:ip]).include? "unable to connect to"
        gradle(task: "installDebug")
      end
    else
      puts "No device target suitable"
    end
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
